### ISSUE TITLE
mirror update-center.json can't identify LTS update

### ISSUE THREAD

**Issue by menggya** [jenkins-zh/update-center-mirror#2]
base version LTS  2.190.1, notify to update LTS 2.190.2 with  http://updates.jenkins-ci.org/update-center.json
but if i change to https://jenkins-zh.gitee.io/update-center-mirror/tsinghua/update-center.json,  then notify to update 2.204,

**Comment by LinuxSuRen** [comment]
I fixed this issue. You can use a new address which is `https://updates.jenkins-zh.cn/update-center.json`.
If you want to know more tech details, please feel free to visit [here](https://github.com/jenkins-zh/mirror-proxy).

**Comment by menggya** [comment]
Another error info, i do check update after i update the  https://updates.jenkins-zh.cn/update-center.json.
update center: Signature verification failed in update site &#039;default&#039; <a href='#' class='showDetails'>（显示详情）</a><pre style='display:none'>java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors<br>	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:153)<br>	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)<br>	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)<br>	at org.jvnet.hudson.crypto.CertificateUtil.validatePath(CertificateUtil.java:93)<br>	at jenkins.util.JSONSignatureValidator.verifySignature(JSONSignatureValidator.java:88)<br>	at hudson.model.UpdateSite.verifySignature(UpdateSite.java:254)<br>	at hudson.model.UpdateSite.updateData(UpdateSite.java:218)<br>	at

**Comment by LinuxSuRen** [comment]
What's the version of your Jenkins?

**Comment by menggya** [comment]
Jenkins ver. 2.190.1

**Comment by LinuxSuRen** [comment]
I just tested it in a new environment with 2.190.1. It's ok. Please make sure that you follow the right flow:
- use the new certificate
- change to the new update center site.

**Comment by lixingmao** [comment]
I also encountered the same problem mentioned above. What does "**use the new certificate**" mean? what should I do?

**Comment by LinuxSuRen** [comment]
You should put [this file](https://github.com/jenkins-zh/mirror-adapter/blob/master/rootCA/mirror-adapter.crt) into your Jenkins. I believe that you can get more details from [here](https://github.com/jenkinsci/localization-zh-cn-plugin/blob/master/src/main/java/io/jenkins/plugins/localization_zh_cn/UpdateCenterAction.java#L34).
