### ISSUE TITLE
签名验证失败是什么原因?需要证书吗?

### ISSUE THREAD

**Issue by AirBashX** [jenkins-zh/update-center-mirror#37]

**Comment by danbao** [comment]
![image](https://user-images.githubusercontent.com/4090783/141727996-819fbd35-2e92-4840-b244-e7211d860714.png)
证书在11月10日过期了

**Comment by yJunS** [comment]
证书已经好了，感谢提醒

**Comment by yJunS** [comment]
如果没有问题的话，我先把issue关闭了
